apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: fitness-tracker
data:
  # Eureka Server
  EUREKA_SERVER_URL: "http://eureka-service:8761/eureka/"
  
  # Config Server
  CONFIG_SERVER_URL: "http://config-server-service:8888"
  
  # Spring Profiles
  SPRING_PROFILES_ACTIVE: "prod"
  
  # Logging
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: "INFO"
