apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: fitness-tracker
type: Opaque
stringData:
  # RDS PostgreSQL
  rds-host: "fitness-tracker-dev-postgres.ctcwa4suov5y.eu-west-1.rds.amazonaws.com"
  rds-port: "5432"
  rds-database: "fitnessdb"
  rds-username: "dbadmin"
  rds-password: "DDaFICt8OW9:2ZPv"
  
  # Self-hosted MongoDB (will be available after deployment)
  mongodb-host: "mongodb-service.fitness-tracker.svc.cluster.local"
  mongodb-port: "27017"
  mongodb-database: "activitydb"
  mongodb-username: "mongouser"
  mongodb-password: "mongopass123"
---
apiVersion: v1
kind: Secret
metadata:
  name: mq-credentials
  namespace: fitness-tracker
type: Opaque
stringData:
  # Amazon MQ RabbitMQ
  rabbitmq-host: "b-28f6f79e-4430-4c3e-acc9-3cf8fc40dbd6.mq.eu-west-1.on.aws"
  rabbitmq-port: "5671"
  rabbitmq-username: "mqadmin"
  rabbitmq-password: "kKFggNTMC$4fBeq{"
  rabbitmq-endpoint: "amqps://b-28f6f79e-4430-4c3e-acc9-3cf8fc40dbd6.mq.eu-west-1.on.aws:5671"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: fitness-tracker
type: Opaque
stringData:
  admin-username: "admin"
  admin-password: "admin123"
  database-password: "keycloakdbpass"
